# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-08 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricecheck', '0002_auto_20180508_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='product',
            field=models.CharField(default='', max_length=100),
        ),
    ]
