# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-08 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricecheck', '0003_alert_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='product',
            new_name='item',
        ),
    ]
