# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-05-08 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricecheck', '0004_auto_20180508_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
